version: '3'

vars:
  TASKFILE_TEMPLATE_URL: "https://git-gst.mto.zing.vn/mps/devops/taskfile-templates.git"

env:
  TASKFILE_TEMPLATE_REF: master

tasks:
  bootstrap:
    desc: "Clone MPS Taskfile templates to .task/templates folder"
    aliases: [bs, "."]
    cmds:
      # See https://stackoverflow.com/questions/4630704/receiving-fatal-not-a-git-repository-when-attempting-to-remote-add-a-git-repo
      - cmd: git config --global --add safe.directory $PWD
      - cmd: |

          url="{{.TASKFILE_TEMPLATE_URL}}"
          if [[ "$CI" == "true" ]]; then
            protocol="${url%%://*}"
            host="${url#*://}"
            url="${protocol}://gitlab-ci-token:${CI_JOB_TOKEN}@${host}"
          fi

          if [ -f ".task/templates/.git/config" ]; then
            cd .task/templates
            git fetch && git reset --hard origin/"$TASKFILE_TEMPLATE_REF"
          else
            git clone -b "$TASKFILE_TEMPLATE_REF" "$url" .task/templates
          fi
      # See https://stackoverflow.com/questions/18329621/how-to-store-a-git-config-as-part-of-the-repository
      - cmd: if [ -f ".task/templates/.gitconfig" ]; then git config include.path ../.task/templates/.gitconfig; fi
